/**
 * Google Drive Integration for Hospital Management System
 * Handles PDF uploads to Google Drive and provides direct download links
 */

class GoogleDriveUploader {
  constructor() {
    this.STORAGE_KEY = 'hospital_gdrive_reports';
    this.API_KEY = null; // Will be set by user
    this.FOLDER_ID = '1COxEHsKChYZAzY2ZQ_Ap969QVlURyXAN'; // Your provided folder ID
  }

  /**
   * Initialize Google Drive API
   * @param {string} apiKey - Google Drive API Key
   * @returns {Promise<boolean>} Success status
   */
  async initialize(apiKey) {
    if (this.API_KEY && this.API_KEY === apiKey) {
      return true; // already initialized
    }

    try {
      this.API_KEY = apiKey;
      
      // Test the API key by checking if we can access the folder
      const response = await fetch(`https://www.googleapis.com/drive/v3/files/${this.FOLDER_ID}?key=${apiKey}`);
      
      if (!response.ok) {
        throw new Error('Invalid API key or insufficient permissions to access the folder');
      }
      
      const folderData = await response.json();
      console.log('✅ Google Drive API initialized. Folder:', folderData.name);
      
      return true;
    } catch (error) {
      console.error('❌ Google Drive initialization failed:', error);
      throw error;
    }
  }

  /**
   * Upload PDF to Google Drive
   * @param {Blob} pdfBlob - PDF file as blob
   * @param {string} filename - Optional filename for the uploaded file
   * @param {Object} meta - Optional metadata object containing reportNumber and patientName
   * @returns {Promise<Object>} Upload result with download link
   */
  async uploadPDF(pdfBlob, filename, meta = {}) {
    try {
      if (!this.API_KEY) throw new Error('Drive not initialized');
      const safeFilename = filename || `Discharge_Report_${meta.reportNumber || Date.now()}.pdf`;
      // Convert blob to base64
      const base64Data = await this.blobToBase64(pdfBlob);
      const base64Content = base64Data.split(',')[1]; // Remove data:application/pdf;base64, prefix
      
      // Upload file
      const uploadResponse = await fetch(
        `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&key=${this.API_KEY}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'multipart/related; boundary="foo_bar_baz"'
          },
          body: this.createMultipartBody(safeFilename, base64Content, meta.reportNumber || 'N/A', meta.patientName || 'Unknown')
        }
      );

      if (!uploadResponse.ok) {
        const errorData = await uploadResponse.json();
        throw new Error(`Upload failed: ${errorData.error?.message || 'Unknown error'}`);
      }

      const uploadData = await uploadResponse.json();
      console.log('✅ PDF uploaded to Google Drive:', uploadData.id);

      // Make file publicly accessible
      await this.makeFilePublic(uploadData.id);

      // Generate direct download link
      const downloadLink = `https://drive.google.com/uc?export=download&id=${uploadData.id}`;
      const viewLink = `https://drive.google.com/file/d/${uploadData.id}/view`;

      // Save to local storage for tracking
      this.saveUploadRecord(meta.reportNumber || uploadData.id, {
        fileId: uploadData.id,
        filename: safeFilename,
        downloadLink: downloadLink,
        viewLink: viewLink,
        patientName: meta.patientName || 'Unknown',
        uploadedAt: new Date().toISOString(),
        fileSize: pdfBlob.size
      });

      return {
        success: true,
        fileId: uploadData.id,
        filename: safeFilename,
        downloadLink: downloadLink,
        viewLink: viewLink
      };

    } catch (error) {
      console.error('❌ Upload error:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Create multipart body for file upload
   */
  createMultipartBody(filename, base64Content, reportNumber, patientName) {
    const boundary = 'foo_bar_baz';
    const metadata = {
      name: filename,
      parents: [this.FOLDER_ID],
      description: `Discharge report for ${patientName} - Report #${reportNumber} - Generated by Hospital Management System`
    };

    const multipartBody = 
      `--${boundary}\r\n` +
      `Content-Type: application/json; charset=UTF-8\r\n\r\n` +
      `${JSON.stringify(metadata)}\r\n` +
      `--${boundary}\r\n` +
      `Content-Type: application/pdf\r\n` +
      `Content-Transfer-Encoding: base64\r\n\r\n` +
      `${base64Content}\r\n` +
      `--${boundary}--`;

    return multipartBody;
  }

  /**
   * Make file publicly accessible
   */
  async makeFilePublic(fileId) {
    try {
      // Check current permissions
      const permissionsResponse = await fetch(
        `https://www.googleapis.com/drive/v3/files/${fileId}/permissions?key=${this.API_KEY}`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json'
          }
        }
      );

      const permissionsData = await permissionsResponse.json();
      const isPublic = permissionsData.permissions && permissionsData.permissions.some(p => p.role === 'reader' && p.type === 'anyone');

      if (isPublic) {
        console.log('✅ File is already publicly accessible');
        return;
      }

      // If not public, set permissions
      const response = await fetch(
        `https://www.googleapis.com/drive/v3/files/${fileId}/permissions?key=${this.API_KEY}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            role: 'reader',
            type: 'anyone'
          })
        }
      );

      if (!response.ok) {
        console.warn('⚠️ Could not make file public, but upload succeeded');
      } else {
        console.log('✅ File made publicly accessible');
      }
    } catch (error) {
      console.warn('⚠️ Could not set public permissions:', error);
    }
  }

  /**
   * Convert blob to base64
   */
  blobToBase64(blob) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }

  /**
   * Save upload record to localStorage
   */
  saveUploadRecord(reportNumber, data) {
    try {
      const stored = JSON.parse(localStorage.getItem(this.STORAGE_KEY) || '{}');
      stored[reportNumber] = data;
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(stored));
    } catch (error) {
      console.warn('⚠️ Could not save upload record to localStorage:', error);
    }
  }

  /**
   * Get all uploaded reports
   */
  getUploadedReports() {
    try {
      return JSON.parse(localStorage.getItem(this.STORAGE_KEY) || '{}');
    } catch (error) {
      console.warn('⚠️ Could not retrieve upload records:', error);
      return {};
    }
  }

  /**
   * Get upload record for specific report
   */
  getUploadRecord(reportNumber) {
    const records = this.getUploadedReports();
    return records[reportNumber] || null;
  }
}

export default GoogleDriveUploader;
